[phases.setup]
apt = [
    "libgdk-pixbuf2.0-0"
    "libxcb-shm0"
    "libxcb-shape0"
    "libxtst6"
    "libx11-xcb1"
    "libxcomposite1"
    "libxdamage1"
    "libxfixes3"
    "libxrandr2"
    "libgbm1"
    "libxss1"
    "libnss3"
    "libatk-bridge2.0-0"
    "libdrm2"
    "libxkbcommon0"
    "libgtk-3-0"
    "libpango-1.0-0"
    "libcairo2"
    "libasound2"
    "libatspi2.0-0"
    "libgtk-3-dev"
]
cmds = [
  "apt-get update -qq && apt-get install -y --no-install-recommends ${apt[*]} && rm -rf /var/lib/apt/lists/*"
]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
#cmds = ["bash start-vnc.sh"]